-- настройки LN3Couch, сохранены из меню игры
return {
  device = "gamepad",
  gamepad = {
    crouch = "Gamepad_LeftTrigger",
    deadzone = 0.2,
    grab = "Gamepad_RightTrigger",
    jump = "Gamepad_FaceButton_Bottom",
    sprint = "Gamepad_FaceButton_Left",
    throw = "Gamepad_RightShoulder",
    weapon = "Gamepad_FaceButton_Right",
  },
  gamepad_goes_to_player2 = false,
  invert_forward = false,
  invert_right = false,
  keyboard = {
    crouch = "RightControl",
    down = "Down",
    grab = "RightShift",
    jump = "Enter",
    left = "Left",
    right = "Right",
    sprint = "Slash",
    throw = "Period",
    up = "Up",
    weapon = "Comma",
  },
  p2_controller_confirmed = false,
  p2_controller_id = 1,
  split_sides = "auto",
  swap_axes = false,
}
